version: "3"

services:
  app:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - .:/src
    command: uvicorn src.main:app --reload --workers 1 --host  "0.0.0.0" --port "8002"
    environment:
      - LOCAL_IP=172.20.47.89
  db:
    image: registry-git.digikala.com/digi-automation/server-codes/ci-cd-boilerplate/mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      # - ./mysql_image:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: jock-app-db
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
