"""initial

Revision ID: eb001512a958
Revises: 
Create Date: 2023-08-20 12:34:36.100109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb001512a958'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scale_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mac', sa.String(length=300), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('pswd', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('admin', 'supernova', name='role'), nullable=True),
    sa.Column('token', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('scales_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(length=300), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['scale_id'], ['scale_entity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scales_weight')
    op.drop_table('users_table')
    op.drop_table('scale_entity')
    # ### end Alembic commands ###
