"""initial

Revision ID: 41c49354605e
Revises: b1777b6236d6
Create Date: 2023-08-10 14:08:47.245713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c49354605e'
down_revision: Union[str, None] = 'b1777b6236d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jocks', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jocks', 'dislikes')
    # ### end Alembic commands ###
